{{- if .Values.authnK8s.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.authnK8s.serviceAccount.name | default "authn-k8s-serviceaccount" }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: authn-k8s-serviceaccount
    app.kubernetes.io/component: authn-k8s-identity
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: "authn-k8s-cluster-config"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end -}}
